### ISSUE TITLE
Foreign classes

### ISSUE THREAD

**Issue by liquidev** [geotre/wren#2]
Wren's all about embedding and object orientation. Some foreign class interface should be provided for this library.

**Comment by geotre** [comment]
Can you give an example of how you would like this interface to work?

**Comment by liquidev** [comment]
My use case is definitely too specific, but I think some kind of macro could be created that would work a bit like this:
```nim
type MyContainer = object
  data: string

proc newContainer(data: string): MyContainer =
  result = MyContainer(data: data)

# with a WrenVM ``vm``:
vm.bindForeignClass[MyContainer](newContainer, nil) # args: constructor and destructor (allocate and finalize)

# the above call would translate to:
proc wren_MyContainer_alloc(vm: ptr WrenVM) {.cdecl.} =
  var point = cast[ptr MyContainer](vm.setSlotNewForeign(0, 0, sizeof(ptr MyContainer)))
  let 
    arg_data = $vm.getSlotString(1)
  point[] = newContainer(arg_data)
```
The code for `wren_MyContainer_alloc` could be automatically generated using a macro that looks for any arguments on the first proc passed to it, and uses the class's data store to store a pointer to the specific instance created by that proc. I know it may sound really verbose, but when you think about how this could be approached, it starts making much more sense.
I can take some time to implement the "universal" solution when I'm done with my "domain-specific" one.

**Comment by geotre** [comment]
Ok I see. I'll think about this. I'm not currently using Wren for any projects, it will be useful to see how you get on with it

**Comment by geotre** [comment]
Closing for now
